// USER
export const STORE_USER_DATA = 'STORE_USER_DATA'

// CART
export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN'
export const ADD_TO_CART = 'ADD_TO_CART'
export const CLEAR_ITEM = 'CLEAR_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const CLEAR_CART = 'CLEAR_CART'

// SHOP
export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS'
